name: flutter_todo_app_r5
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  flutter:
    sdk: flutter

  user_repository:
    path: packages/user_repository
  task_repository:
    path: packages/task_repository

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
